# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            codebyjacob
tagline:          'Cage-free code'
description:      'Just a man without a plan and a little to say.'
url:              http://codebyjacob.com
baseurl:          /

author:
  name:           'Jacob Bolton'
  url:            https://twitter.com/jacobsbolton

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/jsbolton/jsbolton.github.io

# Gems
gems: [jekyll-paginate, jekyll-gist]
paginate: 5
paginate_path: "page:num"

# Sass
sass:
  sass_dir: public/_sass
  style: compressed